name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: deploy
  build:
    runs-on: ubuntu-latest
    steps:
    - name : Check Out Repository
      uses : actions/checkout@v3

      
