name: Deploy
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy  
        run: npm run deploy
